basePath: /  基础路径
info:
  contact: {}
  description: 描述
  title: 标题
  version: 1.0 版本
paths:
  /:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ping GetIndex
      tags:
      - 首页
swagger: "2.0"
